package GUI;

import Controller.Controlar;
import Controller.FuncionarioController;
import Utilitarios.CurrencyFormater;
import java.util.ArrayList;
import java.util.Currency;
import java.util.List;
import javax.swing.JOptionPane;


/**
 * The type Funcionarios form.
 *
 * @author Java
 */
public class FuncionarioForm extends javax.swing.JInternalFrame {

    /**
     * The Currency formater.
     */
    CurrencyFormater currencyFormater = new CurrencyFormater();
    /**
     * The Funcionario c.
     */
    FuncionarioController FuncionarioC = new FuncionarioController();

    /**
     * The Cargo.
     */
    List<String> Cargo;
    /**
     * The Cidades.
     */
    List<String> Cidades;
    /**
     * The Id cidade.
     */
    List<Integer> IdCidade;

    /**
     * The Bairros.
     */
    List<String> Bairros;
    /**
     * The Id bairro.
     */
    List<Integer> IdBairro;

    /**
     * The Ordem.
     */
    List<Integer> Ordem;

    /**
     * Instantiates a new Funcionarios form.
     */
    public FuncionarioForm() {
        initComponents();
        
        Cargo = new ArrayList<>();
        Cidades = new ArrayList<>();
        IdCidade = new ArrayList<>();
        Bairros = new ArrayList<>();
        IdBairro = new ArrayList<>();
        Ordem = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        btnBusscar = new javax.swing.JButton();
        btnMTudo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        cbbCargo = new javax.swing.JComboBox<>();
        cbbCidade = new javax.swing.JComboBox<>();
        cbbBairro = new javax.swing.JComboBox<>();
        btnSair = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edtDataAdm = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        edtDataDem = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edtCarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edtCep = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        edtSalario = new javax.swing.JFormattedTextField();
        chbUsr = new javax.swing.JCheckBox();
        lblLogin = new javax.swing.JLabel();
        edtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblPermissao = new javax.swing.JLabel();
        cbbPermissao = new javax.swing.JComboBox<>();
        edtSenha = new javax.swing.JPasswordField();
        chbAtivo = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        edtCpf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        edtRg = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        chbFun = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        edtSobrenome = new javax.swing.JTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("GUI/Bundle"); // NOI18N
        setTitle(bundle.getString("FuncionarioForm.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cargo", "Salário", "Usuário", "Usuário Ativo", "Funcionário Ativo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblFuncionario.setName("tblFuncionario"); // NOI18N
        jScrollPane1.setViewportView(tblFuncionario);
        if (tblFuncionario.getColumnModel().getColumnCount() > 0) {
            tblFuncionario.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title0_2")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title1_2")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title2_2")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title3_2")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title4_1")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title5_1")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(6).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title6")); // NOI18N
        }

        btnBusscar.setBackground(new java.awt.Color(183, 28, 28));
        btnBusscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBusscar.setText(bundle.getString("FuncionarioForm.btnBusscar.text")); // NOI18N
        btnBusscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusscar.setName("btnBusscar"); // NOI18N
        btnBusscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusscarActionPerformed(evt);
            }
        });

        btnMTudo.setBackground(new java.awt.Color(30, 35, 126));
        btnMTudo.setForeground(new java.awt.Color(255, 255, 255));
        btnMTudo.setText(bundle.getString("FuncionarioForm.btnMTudo.text")); // NOI18N
        btnMTudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMTudo.setName("btnMTudo"); // NOI18N
        btnMTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMTudoActionPerformed(evt);
            }
        });

        jScrollPane2.setEnabled(false);
        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jPanel2.setAutoscrolls(true);
        jPanel2.setName("jPanel2"); // NOI18N

        jSeparator3.setName("jSeparator3"); // NOI18N

        jSeparator4.setName("jSeparator4"); // NOI18N

        cbbCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbbCargo.setEnabled(false);
        cbbCargo.setName("cbbCargo"); // NOI18N

        cbbCidade.setEnabled(false);
        cbbCidade.setName("cbbCidade"); // NOI18N
        cbbCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbCidadeItemStateChanged(evt);
            }
        });
        cbbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbCidadeActionPerformed(evt);
            }
        });

        cbbBairro.setEnabled(false);
        cbbBairro.setName("cbbBairro"); // NOI18N

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/sair-1.png"))); // NOI18N
        btnSair.setToolTipText(bundle.getString("FuncionarioForm.btnSair.toolTipText")); // NOI18N
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setDisabledIcon(null);
        btnSair.setName("btnSair"); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cancel-1.png"))); // NOI18N
        btnCancelar.setToolTipText(bundle.getString("FuncionarioForm.btnCancelar.toolTipText")); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setDisabledIcon(null);
        btnCancelar.setEnabled(false);
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/salvar.png"))); // NOI18N
        btnSalvar.setToolTipText(bundle.getString("FuncionarioForm.btnSalvar.toolTipText")); // NOI18N
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setDisabledIcon(null);
        btnSalvar.setEnabled(false);
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inserir2.png"))); // NOI18N
        btnNovo.setToolTipText(bundle.getString("FuncionarioForm.btnNovo.toolTipText")); // NOI18N
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("FuncionarioForm.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        edtNome.setText(bundle.getString("FuncionarioForm.edtNome.text")); // NOI18N
        edtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtNome.setEnabled(false);
        edtNome.setName("edtNome"); // NOI18N

        jLabel2.setText(bundle.getString("FuncionarioForm.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(bundle.getString("FuncionarioForm.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        edtDataAdm.setEnabled(false);
        edtDataAdm.setName("edtDataAdm"); // NOI18N

        jLabel4.setText(bundle.getString("FuncionarioForm.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        edtDataDem.setEnabled(false);
        edtDataDem.setName("edtDataDem"); // NOI18N

        jLabel5.setText(bundle.getString("FuncionarioForm.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(bundle.getString("FuncionarioForm.jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        edtCarga.setText(bundle.getString("FuncionarioForm.edtCarga.text")); // NOI18N
        edtCarga.setEnabled(false);
        edtCarga.setName("edtCarga"); // NOI18N

        jLabel7.setText(bundle.getString("FuncionarioForm.jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(bundle.getString("FuncionarioForm.jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText(bundle.getString("FuncionarioForm.jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        edtCep.setText(bundle.getString("FuncionarioForm.edtCep.text")); // NOI18N
        edtCep.setEnabled(false);
        edtCep.setName("edtCep"); // NOI18N

        jLabel10.setText(bundle.getString("FuncionarioForm.jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        edtEndereco.setText(bundle.getString("FuncionarioForm.edtEndereco.text")); // NOI18N
        edtEndereco.setEnabled(false);
        edtEndereco.setName("edtEndereco"); // NOI18N

        currencyFormater.CurrencyFormater(edtSalario);
        edtSalario.setText(bundle.getString("FuncionarioForm.edtSalario.text")); // NOI18N
        edtSalario.setEnabled(false);
        edtSalario.setName("edtSalario"); // NOI18N
        edtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSalarioActionPerformed(evt);
            }
        });

        chbUsr.setText(bundle.getString("FuncionarioForm.chbUsr.text")); // NOI18N
        chbUsr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbUsr.setEnabled(false);
        chbUsr.setName("chbUsr"); // NOI18N
        chbUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbUsrActionPerformed(evt);
            }
        });

        lblLogin.setText(bundle.getString("FuncionarioForm.lblLogin.text")); // NOI18N
        lblLogin.setEnabled(false);
        lblLogin.setName("lblLogin"); // NOI18N

        edtLogin.setText(bundle.getString("FuncionarioForm.edtLogin.text")); // NOI18N
        edtLogin.setEnabled(false);
        edtLogin.setName("edtLogin"); // NOI18N

        lblSenha.setText(bundle.getString("FuncionarioForm.lblSenha.text")); // NOI18N
        lblSenha.setEnabled(false);
        lblSenha.setName("lblSenha"); // NOI18N

        lblPermissao.setText(bundle.getString("FuncionarioForm.lblPermissao.text")); // NOI18N
        lblPermissao.setEnabled(false);
        lblPermissao.setName("lblPermissao"); // NOI18N

        cbbPermissao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbbPermissao.setEnabled(false);
        cbbPermissao.setName("cbbPermissao"); // NOI18N
        cbbPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPermissaoActionPerformed(evt);
            }
        });

        edtSenha.setText(bundle.getString("FuncionarioForm.edtSenha.text")); // NOI18N
        edtSenha.setEchoChar('X');
        edtSenha.setEnabled(false);
        edtSenha.setName("edtSenha"); // NOI18N

        chbAtivo.setSelected(true);
        chbAtivo.setText(bundle.getString("FuncionarioForm.chbAtivo.text")); // NOI18N
        chbAtivo.setEnabled(false);
        chbAtivo.setName("chbAtivo"); // NOI18N

        jLabel14.setText(bundle.getString("FuncionarioForm.jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        edtCpf.setText(bundle.getString("FuncionarioForm.edtCpf.text")); // NOI18N
        edtCpf.setEnabled(false);
        edtCpf.setName("edtCpf"); // NOI18N

        jLabel15.setText(bundle.getString("FuncionarioForm.jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        edtRg.setText(bundle.getString("FuncionarioForm.edtRg.text")); // NOI18N
        edtRg.setEnabled(false);
        edtRg.setName("edtRg"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        chbFun.setSelected(true);
        chbFun.setText(bundle.getString("FuncionarioForm.chbFun.text")); // NOI18N
        chbFun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbFun.setEnabled(false);
        chbFun.setName("chbFun"); // NOI18N

        jLabel11.setText(bundle.getString("FuncionarioForm.jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        edtSobrenome.setText(bundle.getString("FuncionarioForm.edtSobrenome.text")); // NOI18N
        edtSobrenome.setEnabled(false);
        edtSobrenome.setName("edtSobrenome"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(55, 55, 55)
                .add(btnNovo)
                .add(18, 18, 18)
                .add(btnSalvar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnCancelar)
                .add(87, 87, 87)
                .add(btnSair, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(115, 115, 115)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(edtNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(54, 54, 54)
                                .add(jLabel11)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(edtSobrenome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(cbbCargo, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(24, 24, 24)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel3)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel7)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9))
                                    .add(jLabel5))
                                .add(35, 35, 35)
                                .add(edtDataAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(23, 23, 23)
                                        .add(lblPermissao)
                                        .add(30, 30, 30))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(33, 33, 33)))
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(edtSalario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(cbbCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(edtCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(chbUsr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(cbbPermissao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(edtCpf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(28, 28, 28)
                                        .add(chbFun)))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel10))
                                .add(34, 34, 34)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(edtEndereco, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .add(edtRg)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .add(chbAtivo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(95, 95, 95))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel4)
                                    .add(jLabel8)
                                    .add(jLabel6))
                                .add(34, 34, 34)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(edtCarga)
                                    .add(cbbBairro, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(edtDataDem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                        .add(53, 53, 53)
                        .add(lblLogin)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(lblSenha)
                        .add(36, 36, 36)
                        .add(edtSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator2)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1))
                .add(130, 130, 130))
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jSeparator3)
                        .add(jSeparator4))
                    .addContainerGap(742, Short.MAX_VALUE)))
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2Layout.createSequentialGroup()
                    .add(114, 114, 114)
                    .add(edtLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(479, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(edtNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(edtSobrenome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel11))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(cbbCargo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jLabel3))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(edtDataDem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jLabel4))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(edtDataAdm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(edtCarga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6)))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(edtSalario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel5)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cbbBairro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cbbCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel8)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(edtCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(edtEndereco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(edtCpf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, edtRg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel15))
                            .add(jLabel14))
                        .add(18, 18, 18))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(chbFun)
                        .add(6, 6, 6)))
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(chbUsr)
                .add(7, 7, 7)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(edtSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblSenha)
                    .add(lblLogin))
                .add(15, 15, 15)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(chbAtivo)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lblPermissao)
                        .add(cbbPermissao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(26, 26, 26)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 56, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(btnNovo)
                        .add(btnSalvar)
                        .add(btnCancelar))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnSair))
                .add(17, 17, 17))
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2Layout.createSequentialGroup()
                    .add(249, 249, 249)
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(108, 108, 108)
                    .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2Layout.createSequentialGroup()
                    .add(305, 305, 305)
                    .add(edtLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel2);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 650, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(90, 90, 90)
                        .add(btnBusscar)
                        .add(18, 18, 18)
                        .add(btnMTudo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 633, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1295, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btnBusscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btnMTudo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 457, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(31, 31, 31))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 578, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName(bundle.getString("FuncionarioForm.AccessibleContext.accessibleName")); // NOI18N

        setBounds(40, 50, 1310, 583);
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Sair form.
     */
    public void sairForm(){
        if (Controlar.fecharForm()) {
            dispose();
        }
    }
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        sairForm();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * Cancelar operacao.
     */
    public void cancelarOperacao() {
      
        Object[] options = {"Sim", "Não"};
        int resp = JOptionPane.showOptionDialog(null, "Deseja Cancelar a inclusão?", "Abortar Operação", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]);

        if (resp == 0) {
            HabilitarCampos(false);
            DesabilitarButton(false);
            LimparCampos();
            chbAtivo.setText("Funcionário");
        } else {
            edtNome.requestFocus();
        }
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelarOperacao();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * Habilitar campos.
     *
     * @param b the b
     */
    public void HabilitarCampos(boolean b){
        
        edtNome.setEnabled(b);
        cbbCargo.setEnabled(b);
        edtDataAdm.setEnabled(b);
        edtDataDem.setEnabled(b);
        cbbCidade.setEnabled(b);
        cbbBairro.setEnabled(b);
        edtCep.setEnabled(b);
        edtEndereco.setEnabled(b);
        edtCpf.setEnabled(b);
        edtRg.setEnabled(b);
        edtSalario.setEnabled(b);
        edtCarga.setEnabled(b);
        chbUsr.setEnabled(b);
        edtSobrenome.setEnabled(b);
        
    }

    /**
     * Habilitar button.
     *
     * @param valor the valor
     */
    final void HabilitarButton(boolean valor) {

        btnNovo.setEnabled(!valor);
        btnSalvar.setEnabled(valor);
        btnBusscar.setEnabled(!valor);
        btnMTudo.setEnabled(!valor);
        btnCancelar.setEnabled(valor);        
        
      
    }
    
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        HabilitarCampos(true);
        BusscarRegistros();
        edtNome.requestFocus();
        HabilitarButton(true);

    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * Usr cred.
     *
     * @param b the b
     */
    public void usrCred(boolean b){
        edtLogin.setEnabled(b);
        edtSenha.setEnabled(b);
        cbbPermissao.setEnabled(b);
        chbAtivo.setEnabled(b);
        
        lblLogin.setEnabled(b);
        lblPermissao.setEnabled(b);
        lblSenha.setEnabled(b);
    }
    
    private void chbUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbUsrActionPerformed
        // TODO add your handling code here:
        
        if(chbUsr.isSelected()){
            chbUsr.setText("Usuário");
            usrCred(true);
            
        } else {
            chbUsr.setText("Funcionário");
            usrCred(false);
        }
    }//GEN-LAST:event_chbUsrActionPerformed

    private void cbbPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPermissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPermissaoActionPerformed

    private void btnBusscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusscarActionPerformed

        
    }//GEN-LAST:event_btnBusscarActionPerformed

    private void btnMTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMTudoActionPerformed

        
    }//GEN-LAST:event_btnMTudoActionPerformed

    private void edtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtSalarioActionPerformed

    private void cbbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbCidadeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbbCidadeActionPerformed

    private void cbbCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbCidadeItemStateChanged
        // TODO add your handling code here:
        Bairros.clear();
        IdBairro.clear();
        cbbBairro.removeAllItems();
        
        FuncionarioC.busscarBairro(IdCidade.get(cbbCidade.getSelectedIndex()), Bairros, IdBairro);
        for(String i: Bairros){
            cbbBairro.addItem(i);
        }
        
       
    }//GEN-LAST:event_cbbCidadeItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnMTudo;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbBairro;
    private javax.swing.JComboBox<String> cbbCargo;
    private javax.swing.JComboBox<String> cbbCidade;
    private javax.swing.JComboBox<String> cbbPermissao;
    private javax.swing.JCheckBox chbAtivo;
    private javax.swing.JCheckBox chbFun;
    private javax.swing.JCheckBox chbUsr;
    private javax.swing.JTextField edtCarga;
    private javax.swing.JTextField edtCep;
    private javax.swing.JTextField edtCpf;
    private com.toedter.calendar.JDateChooser edtDataAdm;
    private com.toedter.calendar.JDateChooser edtDataDem;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtLogin;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtRg;
    private javax.swing.JFormattedTextField edtSalario;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JTextField edtSobrenome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPermissao;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTable tblFuncionario;
    // End of variables declaration//GEN-END:variables

    private void DesabilitarButton(boolean valor) {
        btnNovo.setEnabled(!valor);
        btnSalvar.setEnabled(valor);
        btnBusscar.setEnabled(!valor);
        btnMTudo.setEnabled(!valor);
        btnCancelar.setEnabled(valor);
    }

    private void LimparCampos() {

        edtNome.setText(null);
        edtSobrenome.setText(null);
        cbbCargo.removeAllItems();
        cbbBairro.removeAllItems();
        cbbCidade.removeAllItems();
        
        
    }

    private void BusscarRegistros() {
        Cargo.clear();
        Cidades.clear();
        IdCidade.clear();
        
        FuncionarioC.busscarCargo(Cargo);
        Cargo.forEach((i) -> {
            cbbCargo.addItem(i);
        });
        
        FuncionarioC.busscarCidade(Cidades, IdCidade, Ordem);
        Cidades.forEach((i) -> {
            cbbCidade.addItem(i);
        });
        cbbCidade.setSelectedIndex(Ordem.indexOf(1));
    }
} 
